In [17]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
data = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 402.1 KB

In [19]:
data.head(5)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [20]:
data.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [21]:
attrition_count = data['Attrition'].value_counts()
attrition_rate = (data['Attrition'].value_counts(normalize=True) * 100).round(2).astype(str) + ' %'
print("Rincian Karyawan Resign vs Bertahan:\n", attrition_count)
print("Persentase Karyawan Resign vs Bertahan:\n", attrition_rate)

Rincian Karyawan Resign vs Bertahan:
 Attrition
No     1233
Yes     237
Name: count, dtype: int64
Persentase Karyawan Resign vs Bertahan:
 Attrition
No     83.88 %
Yes    16.12 %
Name: proportion, dtype: str

Data Attrition menunjukan nilai yang sudah memasuki kategori dengan tingkat turnover tinggi yaitu diatas 15%. Riset Gallup dalam reportnya via Evalflow HR Benchmarks 2026 secara konsisten menetapkan bahwa tingkat turnover tahunan di bawah 10% secara umum dianggap "sehat" untuk sebagian besar industri. Mekari Talenta, salah satu penyedia sistem HRIS terbesar di Indonesia, merilis pemetaan turnover yang menetapkan rentang 5% – 10% sebagai Low turnover (stabilitas tinggi), dan 10% – 15% sebagai healthy and balanced turnover.

In [11]:
# 1. Ambil nama kolom yang tipe datanya teks/kategori
kolom_kategorikal = data.select_dtypes(include=['object']).columns

# 2. Hapus 'Attrition' dari daftar looping (karena ini adalah target kita)
# Jika tidak dihapus, nanti ada tabel Attrition vs Attrition (isinya 100% Yes, 100% No)
if 'Attrition' in kolom_kategorikal:
    kolom_kategorikal = kolom_kategorikal.drop('Attrition')

# 3. Lakukan perulangan (looping)
for kolom in kolom_kategorikal:
    print(f"=== Persentase Attrition Berdasarkan: {kolom} (%) ===")
    
    # Gunakan crosstab dengan normalize='index' seperti yang kita pelajari sebelumnya
    tabel_pct = pd.crosstab(data[kolom], data['Attrition'], normalize='index') * 100
    
    # Tampilkan dengan pembulatan 2 angka di belakang koma
    print(tabel_pct.round(2))
    
    print("-" * 50, "\n") # Garis pembatas agar rapi di layar

=== Persentase Attrition Berdasarkan: BusinessTravel (%) ===
Attrition             No    Yes
BusinessTravel
Non-Travel         92.00   8.00
Travel_Frequently  75.09  24.91
Travel_Rarely      85.04  14.96
--------------------------------------------------

=== Persentase Attrition Berdasarkan: Department (%) ===
Attrition                  No    Yes
Department
Human Resources         80.95  19.05
Research & Development  86.16  13.84
Sales                   79.37  20.63
--------------------------------------------------

=== Persentase Attrition Berdasarkan: EducationField (%) ===
Attrition            No    Yes
EducationField
Human Resources   74.07  25.93
Life Sciences     85.31  14.69
Marketing         77.99  22.01
Medical           86.42  13.58
Other             86.59  13.41
Technical Degree  75.76  24.24
--------------------------------------------------

=== Persentase Attrition Berdasarkan: Gender (%) ===
Attrition     No    Yes
Gender
Female     85.20  14.80
Male       82.99  17.01
--------------------------------------------------

=== Persentase Attrition Berdasarkan: JobRole (%) ===
Attrition                     No    Yes
JobRole
Healthcare Representative  93.13   6.87
Human Resources            76.92  23.08
Laboratory Technician      76.06  23.94
Manager                    95.10   4.90
Manufacturing Director     93.10   6.90
Research Director          97.50   2.50
Research Scientist         83.90  16.10
Sales Executive            82.52  17.48
Sales Representative       60.24  39.76
--------------------------------------------------

=== Persentase Attrition Berdasarkan: MaritalStatus (%) ===
Attrition         No    Yes
MaritalStatus
Divorced       89.91  10.09
Married        87.52  12.48
Single         74.47  25.53
--------------------------------------------------

=== Persentase Attrition Berdasarkan: Over18 (%) ===
Attrition     No    Yes
Over18
Y          83.88  16.12
--------------------------------------------------

=== Persentase Attrition Berdasarkan: OverTime (%) ===
Attrition     No    Yes
OverTime
No         89.56  10.44
Yes        69.47  30.53
--------------------------------------------------

C:\Users\lanxn\AppData\Local\Temp\ipykernel_2200\946276248.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  kolom_kategorikal = data.select_dtypes(include=['object']).columns

In [22]:
edu = pd.crosstab(data['Education'], data['Attrition'])
print("=== Tabel Jumlah Attrition Berdasarkan Tingkat Pendidikan ===")
print(edu)
print("\n")

=== Tabel Jumlah Attrition Berdasarkan Tingkat Pendidikan ===
Attrition   No  Yes
Education
1          139   31
2          238   44
3          473   99
4          340   58
5           43    5

In [23]:
overtime = pd.crosstab(data['OverTime'], data['Attrition'])
print("=== Tabel Jumlah Attrition Berdasarkan Tingkat OverTime ===")
print(overtime)
print("\n")

=== Tabel Jumlah Attrition Berdasarkan Tingkat OverTime ===
Attrition   No  Yes
OverTime
No         944  110
Yes        289  127

In [12]:
# 1. Ambil nama kolom yang tipe datanya teks/kategori
kolom_kategorikal = data.select_dtypes(exclude=['number']).columns

# 2. Hapus 'Attrition' dari daftar looping
if 'OverTime' in kolom_kategorikal:
    kolom_kategorikal = kolom_kategorikal.drop('OverTime')

# 3. Lakukan perulangan (looping)
for kolom in kolom_kategorikal:
    print(f"=== Risiko OverTime (YES) Berdasarkan: {kolom} ===")
    
    # Buat tabel persentase seperti biasa
    tabel_pct = pd.crosstab(data[kolom], data['OverTime'], normalize='index') * 100
    
    # TRIK PRO: Ambil HANYA kolom 'Yes', lalu urutkan dari yang terbesar (Descending)
    overtime_yes = tabel_pct['Yes'].sort_values(ascending=False).round(2)
    
    # Tampilkan hasilnya
    print(overtime_yes)
    print("-" * 50, "\n")

=== Risiko OverTime (YES) Berdasarkan: Attrition ===
Attrition
Yes    53.59
No     23.44
Name: Yes, dtype: float64
--------------------------------------------------

=== Risiko OverTime (YES) Berdasarkan: BusinessTravel ===
BusinessTravel
Travel_Frequently    31.05
Travel_Rarely        28.28
Non-Travel           23.33
Name: Yes, dtype: float64
--------------------------------------------------

=== Risiko OverTime (YES) Berdasarkan: Department ===
Department
Sales                     28.70
Research & Development    28.20
Human Resources           26.98
Name: Yes, dtype: float64
--------------------------------------------------

=== Risiko OverTime (YES) Berdasarkan: EducationField ===
EducationField
Other               32.93
Marketing           30.19
Human Resources     29.63
Medical             28.45
Life Sciences       27.56
Technical Degree    25.76
Name: Yes, dtype: float64
--------------------------------------------------

=== Risiko OverTime (YES) Berdasarkan: Gender ===
Gender
Female    30.61
Male      26.76
Name: Yes, dtype: float64
--------------------------------------------------

=== Risiko OverTime (YES) Berdasarkan: JobRole ===
JobRole
Research Scientist           33.22
Sales Representative         28.92
Sales Executive              28.83
Research Director            28.75
Healthcare Representative    28.24
Manufacturing Director       26.90
Manager                      26.47
Human Resources              25.00
Laboratory Technician        23.94
Name: Yes, dtype: float64
--------------------------------------------------

=== Risiko OverTime (YES) Berdasarkan: MaritalStatus ===
MaritalStatus
Divorced    30.28
Single      27.87
Married     27.64
Name: Yes, dtype: float64
--------------------------------------------------

=== Risiko OverTime (YES) Berdasarkan: Over18 ===
Over18
Y    28.3
Name: Yes, dtype: float64
--------------------------------------------------

In [13]:
# Menghitung persentase per baris (Department)
travel_rate = pd.crosstab(data['Department'], data['BusinessTravel'], normalize='index') * 100

# Membulatkan dan menambahkan tanda %
travel_rate.round(2).astype(str) + '%'

BusinessTravel         Non-Travel Travel_Frequently Travel_Rarely
Department
Human Resources             9.52%            17.46%        73.02%
Research & Development     10.09%            18.94%        70.97%
Sales                      10.54%            18.83%        70.63%